### ISSUE TITLE
Usage with multiple files

### ISSUE THREAD

**Issue by 20Fourteen** [joshpangell/single-use#16]
How would I use this with multiple files?

Thanks

**Comment by OpticDreams** [comment]
I was wondering that, myself. 
I assume (this is just theory) one could generate a key for each item by adding the corresponding file directory in the variable script and then generating the key, saving it and repeating the process with the next file using the same variable script. then backing up all your generated keys offline in case you require them in the future.

**Comment by joshpangell** [comment]
The most obvious way to use one key with multiple files would be to zip the files together. 

If you wanted to have separate files, then you would need to create unique download links for each file. This is because we use the `header` as an output buffer and you can only do that one per session. Meaning, you can only force a single download from a single link because that is the way HTTP works. 

I made a branch of this code to show how you would create a multi-file download. [Here it is](https://github.com/joshpangell/single-use/tree/multifile).

[Example](http://cloud.joshpangell.com/singleuse/multifile/)

**Comment by joshpangell** [comment]
Update: I've merged the multifile feature branch into the master. I've also included the full demo with styling.

**Comment by OpticDreams** [comment]
Haven't tried it just yet, but so far your scripts have been super.
