### ISSUE TITLE
Doesn't work with large files.

### ISSUE THREAD

**Issue by jhaleit** [joshpangell/single-use#17]
It doesn't work with large files... I get a 500 error when trying to do anything above 50mb.

**Comment by joshpangell** [comment]
This is likely because your server config is blocking anything over that size. The script itself is forcing the connection to stay open indefinitely by using `set_time_limit(0);` and `header("Expires: 0");`

If you are on Apache, check into setting [LimitRequestBody](http://httpd.apache.org/docs/2.2/mod/core.html#limitrequestbody) to `0`

If you are using nginx, see [proxy_max_temp_file_size](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_max_temp_file_size)
