### ISSUE TITLE
How to add auto load function?

### ISSUE THREAD

**Issue by MIMAXUZ** [joshpangell/single-use#25]
Hey, How can I add auto load function then I need automaticly read all files from /download/ ?
Can I do that?
But I tried with IS_DIR no solution, Any way for doing that?

**Comment by joshpangell** [comment]
One of the purposes of this script was to be able to mask the _actual_ file name with anything you'd like. However, if you don't care about that, then you could simply read the filenames and output those. 

The `$PROTECTED_DOWNLOADS` value in `variables.php` is an array of files. Instead of looping through this list, you could loop through the files of a directory using [scandir](http://php.net/manual/en/function.scandir.php).
