### ISSUE TITLE
Refresh browser allows for multiple downloads

### ISSUE THREAD

**Issue by marvmckay** [joshpangell/single-use#3]
It seems that if I simply refresh the browser, it allows multiple downloads.  The key is different each time, but it doesn't stop me from downloading again.

Also, if I simply copy and paste the URL:
http://cloud.joshpangell.com/singleuse/generate.php?1234
into different browsers, again I can download the file more than once.

**Comment by OpticDreams** [comment]
russellhutsonmicro-p, the problem with that method, is that the process isn't automated. in order to make revenue from such process, you must manually send a key to everyone who buys a song from you. you cannot attach it to a link, since it would only allow for only one download. I believe what marvmckay was after, is a system that would execute/run the key (triggering the download), instead of displaying it so it can be attached to a paypal (or similar) button that would redirect the user to a one time path using the single key generated. this method would make use of the generator as the output device rather than the key code itself.
